export const DREAMSCAPES = [
  "A red door in an empty white room.",
  "A chair floating in dark water.",
  "Your old school but all the doors are too small.",
  "A mirror that shows someone else's reflection.",
  "An empty street with all the streetlights flickering.",
  "A single tree growing through the floor of your living room.",
  "A hallway that gets narrower the further you walk.",
  "Your bed floating in the middle of a vast field.",
  "A phone booth ringing in the middle of nowhere.",
  "An elevator with buttons for floors that don't exist.",
  "A familiar face on a stranger's body.",
  "A room where gravity points sideways.",
  "Your car driving itself down an endless highway.",
  "A door that opens onto the same room you're already in.",
  "A clock with hands that move backwards.",
  "Your mother's voice calling from an empty house.",
  "A staircase that leads down into bright light.",
  "A window that shows outside but you're already outside.",
  "A pen that writes words you didn't think.",
  "A shadow that moves independently of your body.",
  "A misty, undefined space where thoughts take shape and dissolve like morning fog.",
  "An endless library with books that whisper secrets when you approach their spines.",
  "Your childhood bedroom, but the walls breathe and the ceiling stretches infinitely upward.",
  "A staircase that spirals both up and down simultaneously, leading to doors that open onto memories.",
  "A forest where the trees are made of crystallized time and their leaves chime with forgotten conversations.",
  "An abandoned shopping mall where mannequins move when you're not looking directly at them.",
  "A house with rooms that rearrange themselves each time you turn around.",
  "An ocean of warm, luminous water that you can breathe, filled with floating islands of furniture.",
  "A city street that stretches endlessly in both directions, populated by people you almost recognize.",
  "A school hallway where lockers contain portals to different moments in your life.",
  "A carnival at twilight where all the rides operate in impossible ways and the mirrors show different faces.",
  "A kitchen where ingredients cook themselves and meals transform into memories as you eat them.",
  "A theater where you're simultaneously the audience, the performer, and the stage itself.",
  "A garden where flowers bloom into miniature worlds and their petals are made of compressed starlight.",
  "An elevator that travels through dimensions instead of floors, each button labeled with an emotion.",
  "A bridge spanning a chasm of swirling colors that sing when the wind passes through them.",
  "A winter landscape where the snow falls upward and each flake contains a frozen moment of joy.",
  "A cave system where the walls are lined with television screens showing scenes from possible futures.",
  "A playground where the swings carry you through different seasons with each arc.",
  "A desert where the sand dunes shift to reveal buried childhood toys that pulse with their own inner light.",
] as const;

export type Dreamscape = string; 